#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Mar 21, 2022 03:12:42 PM +06  platform: Windows NT
#    Mar 21, 2022 03:58:40 PM +06  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import korzina


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = korzina.Toplevel1(_top1)
    root.mainloop()


def opening1():
    root.mainloop()
    import катал


def opening2():
    root.mainloop()
    import zakaz


def opening3():
    import spr


def opening4():
    import razrab


def delete1():
    root.mainloop()
    import korzina1


def delete2():
    root.mainloop()
    import korzina2


if __name__ == '__main__':
    korzina.start_up()
