import pathlib
import pygubu
import tkinter as tk
import tkinter.ttk as ttk
from pygubu.widgets.scrolledframe import ScrolledFrame

PROJECT_PATH = pathlib.Path(__file__).parent
PROJECT_UI = PROJECT_PATH / "AKSSSSANIII.ui"

class AkssssaniiiApp:
    def __init__(self, master=None):
        # build ui
        self.toplevel2 = tk.Toplevel(master, container='false')
        self.scrolledframe17 = ScrolledFrame(self.toplevel2, scrolltype='both')
        self.label23 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_7 = tk.PhotoImage(file='7.png')
        self.label23.configure(image=self.img_7, text='label23')
        self.label23.place(anchor='nw', relx='0.04', rely='0.05', x='0', y='0')
        self.label24 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_1 = tk.PhotoImage(file='1.png')
        self.label24.configure(image=self.img_1, text='label24')
        self.label24.place(anchor='nw', relx='0.39', rely='0.05', x='0', y='0')
        self.label25 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_5 = tk.PhotoImage(file='5.png')
        self.label25.configure(image=self.img_5, text='label25')
        self.label25.place(anchor='nw', relx='0.73', rely='0.05', x='0', y='0')
        self.label26 = ttk.Label(self.scrolledframe17.innerframe)
        self.label26.configure(anchor='center', font='{Segoe UI} 13 {}', justify='center', relief='flat')
        self.label26.configure(takefocus=False, text='Кепка PUMA')
        self.label26.place(anchor='nw', bordermode='inside', height='20', relx='0.09', rely='0.02')
        self.label27 = ttk.Label(self.scrolledframe17.innerframe)
        self.label27.configure(font='{Segoe UI} 13 {}', text='Кепка NIKE')
        self.label27.place(anchor='nw', height='20', relx='0.445', rely='0.02', x='0', y='0')
        self.label28 = ttk.Label(self.scrolledframe17.innerframe)
        self.label28.configure(font='{Segoe UI} 13 {}', text='Кепка NORTH FACE')
        self.label28.place(anchor='nw', height='20', relx='0.75', rely='0.02', x='0', y='0')
        self.button1 = ttk.Button(self.scrolledframe17.innerframe)
        self.button1.configure(text='Добавить в корзину')
        self.button1.place(anchor='nw', relx='0.075', rely='0.27', x='0', y='0')
        self.label1 = ttk.Label(self.scrolledframe17.innerframe)
        self.label1.configure(takefocus=False)
        self.label1.grid(column='0', row='0')
        self.label2 = ttk.Label(self.scrolledframe17.innerframe)
        self.label2.grid(column='0', row='1')
        self.label3 = ttk.Label(self.scrolledframe17.innerframe)
        self.label3.grid(column='0', row='2')
        self.label4 = ttk.Label(self.scrolledframe17.innerframe)
        self.label4.grid(column='0', row='3')
        self.label5 = ttk.Label(self.scrolledframe17.innerframe)
        self.label5.grid(column='0', row='4')
        self.label6 = ttk.Label(self.scrolledframe17.innerframe)
        self.label6.grid(column='0', row='5')
        self.label7 = ttk.Label(self.scrolledframe17.innerframe)
        self.label7.grid(column='0', row='6')
        self.label8 = ttk.Label(self.scrolledframe17.innerframe)
        self.label8.configure(text='\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        self.label8.grid(column='0', row='7')
        self.label9 = ttk.Label(self.scrolledframe17.innerframe)
        self.label9.grid(column='0', row='8')
        self.label10 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_6 = tk.PhotoImage(file='6.png')
        self.label10.configure(image=self.img_6, text='label10')
        self.label10.place(anchor='nw', relx='0.04', rely='0.35', x='0', y='0')
        self.label11 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_41 = tk.PhotoImage(file='4 (1).png')
        self.label11.configure(image=self.img_41, text='label11')
        self.label11.place(anchor='nw', relx='0.39', rely='0.35', x='0', y='0')
        self.label12 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_2 = tk.PhotoImage(file='2.png')
        self.label12.configure(image=self.img_2, text='label12')
        self.label12.place(anchor='nw', relx='0.73', rely='0.35', x='0', y='0')
        self.label13 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_8 = tk.PhotoImage(file='8.png')
        self.label13.configure(image=self.img_8, text='label13')
        self.label13.place(anchor='nw', relx='0.04', rely='0.65', x='0', y='0')
        self.label14 = ttk.Label(self.scrolledframe17.innerframe)
        self.label14.grid(column='0', row='13')
        self.label15 = ttk.Label(self.scrolledframe17.innerframe)
        self.label15.configure(font='{Segoe UI} 13 {}', text='Кепка RAVENA')
        self.label15.place(anchor='nw', relx='0.084', rely='0.32', x='0', y='0')
        self.label16 = ttk.Label(self.scrolledframe17.innerframe)
        self.label16.configure(font='{Segoe UI} 13 {}', text='Кепка AKSSSANI')
        self.label16.place(anchor='nw', relx='0.42', rely='0.32', x='0', y='0')
        self.label17 = ttk.Label(self.scrolledframe17.innerframe)
        self.label17.configure(font='{Segoe UI} 13 {}', text='Кепка LAOCHRA')
        self.label17.place(anchor='nw', relx='0.76', rely='0.32', x='0', y='0')
        self.label21 = ttk.Label(self.scrolledframe17.innerframe)
        self.label21.configure(text='\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        self.label21.grid(column='0', row='20')
        self.button2 = ttk.Button(self.scrolledframe17.innerframe)
        self.button2.configure(text='Добавить в корзину')
        self.button2.place(anchor='nw', relx='0.43', rely='0.27', x='0', y='0')
        self.button3 = ttk.Button(self.scrolledframe17.innerframe)
        self.button3.configure(text='Добавить в корзину')
        self.button3.place(anchor='nw', relx='0.77', rely='0.27', x='0', y='0')
        self.button4 = ttk.Button(self.scrolledframe17.innerframe)
        self.button4.configure(text='Добавить в корзину')
        self.button4.place(anchor='nw', relx='0.43', rely='0.57', x='0', y='0')
        self.button5 = ttk.Button(self.scrolledframe17.innerframe)
        self.button5.configure(text='Добавить в корзину')
        self.button5.place(anchor='nw', relx='0.075', rely='0.57', x='0', y='0')
        self.button6 = ttk.Button(self.scrolledframe17.innerframe)
        self.button6.configure(text='Добавить в корзину')
        self.button6.place(anchor='nw', relx='0.77', rely='0.57', x='0', y='0')
        self.label51 = ttk.Label(self.scrolledframe17.innerframe)
        self.label51.configure(font='{Segoe UI} 13 {}', text='Кепка BlackHawk')
        self.label51.place(anchor='nw', relx='0.07', rely='0.62', x='0', y='0')
        self.button7 = ttk.Button(self.scrolledframe17.innerframe)
        self.button7.configure(text='Добавить в корзину')
        self.button7.place(anchor='nw', relx='0.075', rely='0.87', x='0', y='0')
        self.label52 = ttk.Label(self.scrolledframe17.innerframe)
        self.label52.configure(font='{Segoe UI} 13 {}', text='Кепка KINZA')
        self.label52.place(anchor='nw', relx='0.45', rely='0.62', x='0', y='0')
        self.label53 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_9 = tk.PhotoImage(file='9.png')
        self.label53.configure(image=self.img_9, justify='right', text='label53')
        self.label53.place(anchor='nw', relx='0.39', rely='0.65', x='0', y='0')
        self.label54 = ttk.Label(self.scrolledframe17.innerframe)
        self.img_3 = tk.PhotoImage(file='3.png')
        self.label54.configure(image=self.img_3, text='label54')
        self.label54.place(anchor='nw', relx='0.73', rely='0.65', x='0', y='0')
        self.label55 = ttk.Label(self.scrolledframe17.innerframe)
        self.label55.configure(font='{Segoe UI} 13 {}', text='Кепка KAMARR')
        self.label55.place(anchor='nw', relx='0.76', rely='0.62', x='0', y='0')
        self.button8 = ttk.Button(self.scrolledframe17.innerframe)
        self.button8.configure(text='Добавить в корзину')
        self.button8.place(anchor='nw', relx='0.43', rely='0.87', x='0', y='0')
        self.button9 = ttk.Button(self.scrolledframe17.innerframe)
        self.button9.configure(text='Добавить в корзину')
        self.button9.place(anchor='nw', relx='0.77', rely='0.87', x='0', y='0')
        self.label57 = ttk.Label(self.scrolledframe17.innerframe)
        self.label57.configure(font='{Segoe UI} 12 {}', text='4999 тг.')
        self.label57.place(anchor='nw', relx='0.12', rely='0.24', x='0', y='0')
        self.label58 = ttk.Label(self.scrolledframe17.innerframe)
        self.label58.configure(font='{Segoe UI} 12 {}', text='4499 тг.')
        self.label58.place(anchor='nw', relx='0.47', rely='0.24', x='0', y='0')
        self.label59 = ttk.Label(self.scrolledframe17.innerframe)
        self.label59.configure(font='{Segoe UI} 12 {}', text='5499 тг.')
        self.label59.place(anchor='nw', relx='0.81', rely='0.24', x='0', y='0')
        self.label62 = ttk.Label(self.scrolledframe17.innerframe)
        self.label62.configure(font='{Segoe UI} 12 {}', text='3499 тг.')
        self.label62.place(anchor='nw', relx='0.12', rely='0.54', x='0', y='0')
        self.label63 = ttk.Label(self.scrolledframe17.innerframe)
        self.label63.configure(font='{Segoe UI} 12 {}', text='4999 тг.')
        self.label63.place(anchor='nw', relx='0.12', rely='0.84', x='0', y='0')
        self.label64 = ttk.Label(self.scrolledframe17.innerframe)
        self.label64.configure(font='{Segoe UI} 12 {}', text='4499 тг.')
        self.label64.place(anchor='nw', relx='0.47', rely='0.54', x='0', y='0')
        self.label65 = ttk.Label(self.scrolledframe17.innerframe)
        self.label65.configure(font='{Segoe UI} 12 {}', text='4999 тг.')
        self.label65.place(anchor='nw', relx='0.81', rely='0.54', x='0', y='0')
        self.label66 = ttk.Label(self.scrolledframe17.innerframe)
        self.label66.configure(font='{Segoe UI} 12 {}', text='5999 тг.')
        self.label66.place(anchor='nw', relx='0.47', rely='0.84', x='0', y='0')
        self.label67 = ttk.Label(self.scrolledframe17.innerframe)
        self.label67.configure(font='{Segoe UI} 12 {}', text='3999 тг.')
        self.label67.place(anchor='nw', relx='0.81', rely='0.84', x='0', y='0')
        self.button10 = ttk.Button(self.scrolledframe17.innerframe)
        self.button10.configure(text='ПЕРЕЙТИ К КОРЗИНЕ')
        self.button10.place(anchor='nw', relx='0.42', rely='0.93', x='0', y='0')
        self.scrolledframe17.configure(usemousewheel=False)
        self.scrolledframe17.place(anchor='nw', height='461', relheight='0.0', relwidth='0.0', relx='0.0', rely='0.28',
                                   width='800', x='0', y='0')
        self.label60 = ttk.Label(self.toplevel2)
        self.label60.configure(background='#f0f0f0', font='{Segoe UI Emoji} 18 {}', text='КАТАЛОГ ТОВАРОВ')
        self.label60.place(anchor='nw', relx='0.38', rely='0.19', x='0', y='0')
        self.label61 = ttk.Label(self.toplevel2)
        self.img_imgonlinecomuaResizeQzO7HQKLLg8UE4 = tk.PhotoImage(file='imgonline-com-ua-Resize-QzO7HQKLLg8UE4.png')
        self.label61.configure(image=self.img_imgonlinecomuaResizeQzO7HQKLLg8UE4, text='label61')
        self.label61.place(anchor='nw', relx='0.24', rely='0.06', x='0', y='0')
        self.toplevel2.configure(background='#f0f0f0', cursor='arrow', height='200', relief='flat')
        self.toplevel2.configure(width='200')
        self.toplevel2.geometry('800x641')
        self.toplevel2.resizable(True, True)


        # Main widget
        self.mainwindow = self.toplevel2

    def run(self):
        self.mainwindow.mainloop()


if __name__ == '__main__':
    app = AkssssaniiiApp()
    app.run()


